### ISSUE TITLE
hacktoberfest-accepted label must be needed

### ISSUE THREAD

**Issue by kambleaa007** [ShahinaShanu/FoodDeliveryProject#4]
Your pull request will undergo a review period in which the repository will be checked for the Hacktoberfest topic or has a hacktoberfest-accepted label on it. We will continue to check this pull request and repository until November 1 for the hacktoberfest topic. If the topic is added to the repository, the pull request will become valid.

[More Info](https://hacktoberfest.digitalocean.com/faq)

**Comment by ShahinaShanu** [comment]
Thanks for providing me more information about hacktoberfest.
